### ISSUE TITLE
EGTEA and Epic-Kitchens-55

### ISSUE THREAD

**Issue by richwardle** [zhanghaotong1/WSLVideoDenseAnticipation#1]
Hi, This isn't an issue, just interested in the progress of running the model for these datasets? Thanks

**Comment by zhanghaotong1** [comment]
Hi, thanks for your interest in our project. There was some delays in this process and unfortunately I do not have access to the GPUs now. I may restart the process if I find new GPUs. If you need the results, you may train our model on the datasets by yourself. My deep apologies for the inconvenience.

**Comment by deadlykitten4** [comment]
Hi, have you ran the model for these dataset?
