### ISSUE TITLE
Inquiry about the data

### ISSUE THREAD

**Issue by deadlykitten4** [zhanghaotong1/WSLVideoDenseAnticipation#2]
Hi, I want to reproduce your work, could you please provide the data you use? Cause I want to run your model on Epickitchens dataset, I want to use your data as a reference. Thank you!

**Comment by zhanghaotong1** [comment]
Hi, thanks for your interest in our work. Unfortunately I do not have the data now. You may want to contact the author of ECCV 2020 (the paper I listed in README) for the original data.

**Comment by deadlykitten4** [comment]
Oh, I see that. Thanks a lot!

**Comment by deadlykitten4** [comment]
Hi, I still have a problem that if you have files that used in the code below? If you have, could you please send me that? I really appreciate it.

self.GT_folder = os.path.join(self.path, 'groundTruth/')
self.mapping = os.path.join(self.path, 'mapping.txt')
self.full_split = os.path.join(self.path, 'split/full.split3.bundle')
self.weak_split = os.path.join(self.path, 'split/weak.split3.bundle')
self.test_split = os.path.join(self.path, 'split/test.split.bundle')

**Comment by zhanghaotong1** [comment]
Sorry I don't have.
